export const languages = [
  "Afrikaans",
  "العربية (Arabic)",
  "azərbaycan (Azerbaijani)",
  "বাংলা (Bangla)",
  "bosanski (Bosnian)",
  "català (Catalan)",
  "Čeština (Czech)",
  "Dansk (Danish)",
  "Deutsch (German)",
  "English (United Kingdom)",
  "English (United States)",
  "Español (Spain)",
  "Español (Latinoamérica)",
  "Eesti (Estonian)",
  "Filipino",
  "Français (France)",
  "Français (Canada)",
  "Galego (Galician)",
  "Hrvatski (Croatian)",
  "Indonesia (Indonesian)",
  "Íslenska (Icelandic)",
  "Italiano (Italian)",
  "Kiswahili (Swahili)",
  "Latviešu (Latvian)",
  "Lietuvių (Lithuanian)",
  "Magyar (Hungarian)",
  "Melayu (Malay)",
  "Nederlands (Dutch)",
  "Norsk (Norwegian)",
  "Polski (Polish)",
  "Português (Brasil)",
  "Português (Portugal)",
  "Română (Romanian)",
  "Slovenčina (Slovak)",
  "Slovenščina (Slovenian)",
  "Suomi (Finnish)",
  "Svenska (Swedish)",
  "Türkçe (Turkish)",
  "Українська (Ukrainian)",
  "日本語 (Japanese)",
  "한국어 (Korean)",
  "中文 (简体) (Simplified Chinese)",
  "中文 (繁體) (Traditional Chinese)"
];
